version: '3.8'

services:

  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"

      - "--providers.docker=true"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.traefik.address=:8080"
      # logs
      - "--accesslog=true"
      - "--accesslog.format=json"

      #metrics
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entrypoint=metrics"
      - "--entrypoints.metrics.address=:8082"

    ports:
      - "80:80"
      - "8081:8080"
      - "8082:8082"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686"
      - "6831:6831/udp"
  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: encurtador-url
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`encurtador.localhost`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=8080"